/* ===== SHYRAQ EDUCATION — OFFICIAL UNIVERSITY SEED =====
   Source: ENIC Kazakhstan, Қазақстан Республикасының жоғары және жоғары оқу орнынан кейінгі білім беру ұйымдарының тізімі
   Source URL: https://enic-kazakhstan.edu.kz/reference_information/universities
   Logo policy: do not hotlink external logos. Upload verified official logos to platform storage,
   then save the storage URL in logo_url and the original official source in logo_source_url.
*/

window.UNIVERSITIES_SCHEMA = [
  'id',
  'name_kz',
  'name_ru',
  'name_en',
  'short_name',
  'city',
  'official_website',
  'logo_url',
  'logo_source_url',
  'description',
  'university_type',
  'category',
  'status',
  'created_at',
  'updated_at'
];

window.UNIVERSITY_LOGO_POLICY = {
  allowHotlink: false,
  acceptedSources: [
    'university official website',
    'brandbook',
    'media resources',
    'press kit',
    'official PDF or brand guideline',
    'official social media or official document'
  ],
  placeholderLabel: 'Логотип қосылмаған'
};

window.UNIVERSITIES_SEED = [
  {
    "id": 1,
    "name_kz": "\"Bolashaq\"Академиясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 2,
    "name_kz": "\"Болашақ\" Қызылорда университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 3,
    "name_kz": "\"Мирас\"Университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 4,
    "name_kz": "\"Нұр-Мүбарак\"Египет ислам мәдениеті университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 5,
    "name_kz": "\"Тұран-Астана\" Университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 6,
    "name_kz": "Alikhan Bokeikhan University",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 7,
    "name_kz": "Astana IT University",
    "name_ru": null,
    "name_en": null,
    "short_name": "AITU",
    "city": "Астана",
    "official_website": "https://astanait.edu.kz/",
    "logo_url": "assets/university-logos/aitu-university.svg",
    "logo_source_url": "https://astanait.edu.kz/",
    "description": null,
    "university_type": "жеке",
    "category": "IT",
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 8,
    "name_kz": "Esil University",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 9,
    "name_kz": "SDU University",
    "name_ru": null,
    "name_en": null,
    "short_name": "SDU",
    "city": "Қаскелен",
    "official_website": "https://sdu.edu.kz/",
    "logo_url": "assets/university-logos/sdu-university.svg",
    "logo_source_url": "https://sdu.edu.kz/",
    "description": "SDU University — Қаскелен қаласында орналасқан, технология мен жауапты білімге басымдық беретін халықаралық жеке университет.",
    "university_type": "жеке",
    "category": "IT / бизнес",
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 10,
    "name_kz": "«Қоғамдық денсаулық сақтау жоғары мектебі» қазақстандық медицина университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 11,
    "name_kz": "Ілияс Жансүгіров атындағы Жетісу университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 12,
    "name_kz": "А. Байтұрсынов атындағы Қостанай Өңірлік университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 13,
    "name_kz": "Абай Мырзахметов атындағы Көкшетау университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 14,
    "name_kz": "Абай атындағы Қазақ ұлттық педагогикалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": "ABAI",
    "city": "Алматы",
    "official_website": "https://www.abai.university/",
    "logo_url": "assets/university-logos/abai-university.svg",
    "logo_source_url": "https://www.abai.university/",
    "description": "Абай университеті — Қазақстандағы алғашқы педагогикалық жоғары оқу орындарының бірі, білім беру және педагогика бағытындағы жетекші университет.",
    "university_type": "мемлекеттік",
    "category": "педагогика",
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 15,
    "name_kz": "Абылай хан атындағы Қазақ халықаралық қатынастар және әлем тілдері университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 16,
    "name_kz": "Азаматтық авиация академиясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 17,
    "name_kz": "Академик А. Қуатбеков атындағы Халықтар Достығы университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 18,
    "name_kz": "Академик Е. А. Бөкетов атындағы Қарағанды университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 19,
    "name_kz": "Академик Зулхарнай Алдамжар атындағы Қостанай әлеуметтік-техникалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 20,
    "name_kz": "Академик Қ. Сәтбаев атындағы Екібастұз инженерлік-техникалық институты",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 21,
    "name_kz": "Алматы гуманитарлық-экономикалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 22,
    "name_kz": "Алматы менеджмент университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": "AlmaU",
    "city": "Алматы",
    "official_website": "https://almau.edu.kz/",
    "logo_url": "assets/university-logos/almau-university.svg",
    "logo_source_url": "https://almau.edu.kz/",
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 23,
    "name_kz": "Алматы технологиялық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 24,
    "name_kz": "Астана медицина университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 25,
    "name_kz": "Астана халықаралық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 26,
    "name_kz": "Атырау инженерлік-гуманитарлық институты",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 27,
    "name_kz": "Баишев Университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 28,
    "name_kz": "Батыс Қазақстан инновациялық-технологиялық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 29,
    "name_kz": "Гуманитарлық-техникалық академиясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 30,
    "name_kz": "Д. Серікбаев атындағы Шығыс Қазақстан техникалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 31,
    "name_kz": "Де Монтфорт Юниверсити Қазақстан",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 32,
    "name_kz": "Дене шынықтыру және бұқаралық спорт академиясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 33,
    "name_kz": "Еуразия гуманитарлық институты",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 34,
    "name_kz": "Еуразиялық технологиялық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 35,
    "name_kz": "Жұмабек Ахметұлы Тәшенев атындағы Университет",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 36,
    "name_kz": "Жәңгір хан атындағы Батыс Қазақстан аграрлық-техникалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 37,
    "name_kz": "Инновациялық Еуразия университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 38,
    "name_kz": "КИМЭП Университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 39,
    "name_kz": "Каспий қоғамдық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 40,
    "name_kz": "Кенжеғали Сағадиев атындағы Халықаралық бизнес университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 41,
    "name_kz": "Л. Б. Гончаров атындағы Қазақ автомобиль-жол институты",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 42,
    "name_kz": "Л. Н. Гумилев атындағы Еуразия ұлттық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": "ЕҰУ",
    "city": "Астана",
    "official_website": "https://enu.kz/",
    "logo_url": "assets/university-logos/enu-university.svg",
    "logo_source_url": "https://enu.kz/",
    "description": null,
    "university_type": "мемлекеттік",
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 43,
    "name_kz": "Логистика және көлік академиясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 44,
    "name_kz": "М. Дулатов атындағы Қостанай инженерлік-экономикалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 45,
    "name_kz": "М. С. Нәрікбаев атындағы КАЗГЮУ университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 46,
    "name_kz": "М. Х. Дулати атындағы Тараз өңірлік университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 47,
    "name_kz": "М. Қозыбаев атындағы Солтүстік Қазақстан университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 48,
    "name_kz": "М. Әуезов атындағы Оңтүстік Қазақстан университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 49,
    "name_kz": "Марат Оспанов атындағы Батыс Қазақстан медициналық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 50,
    "name_kz": "Махамбет Өтемісов атындағы Батыс Қазақстан университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 51,
    "name_kz": "Нархоз Университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 52,
    "name_kz": "О. А. Байқоңыров атындағы Жезқазған университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 53,
    "name_kz": "Орталық Азия Инновациялық Университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 54,
    "name_kz": "Орталық Қазақстан академиясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 55,
    "name_kz": "Оңтүстік Қазақстан медицина академиясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 56,
    "name_kz": "Оңтүстік Қазақстан мемлекеттік педагогикалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 57,
    "name_kz": "Рудный индустриалды институты",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 58,
    "name_kz": "С. Д. Асфендияров атындағы Қазақ ұлттық медицина университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 59,
    "name_kz": "С. Сейфуллин атындағы Қазақ агротехникалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 60,
    "name_kz": "С. Өтебаев атындағы Атырау Мұнай және газ университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 61,
    "name_kz": "Семей медициналық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 62,
    "name_kz": "Семей қаласының Шәкәрім атындағы университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 63,
    "name_kz": "Сәрсен Аманжолов атындағы Шығыс Қазақстан университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 64,
    "name_kz": "Торайғыров университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 65,
    "name_kz": "Тұран \" Университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 66,
    "name_kz": "Х. Досмұхамедов атындағы Атырау университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 67,
    "name_kz": "Халықаралық ақпараттық технологиялар университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 68,
    "name_kz": "Халықаралық білім беру корпорациясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 69,
    "name_kz": "Халықаралық инженерлік-технологиялық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 70,
    "name_kz": "Халықаралық көлік-гуманитарлық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 71,
    "name_kz": "Халықаралық туризм және қонақжайлылық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 72,
    "name_kz": "Ш. Есенов атындағы Каспий технологиялар және инжиниринг университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 73,
    "name_kz": "Ш. Уәлиханов атындағы Көкшетау университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 74,
    "name_kz": "Шерхан Мұртаза атындағы Халықаралық Тараз Инновациялық институты",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 75,
    "name_kz": "Шымкент университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 76,
    "name_kz": "Ы. Алтынсарин атындағы Арқалық педагогикалық институты",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 77,
    "name_kz": "Ғұмарбек Дәукеев атындағы Алматы энергетика және байланыс университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 78,
    "name_kz": "Қ. А. Ясауи атындағы Халықаралық қазақ-түрік университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 79,
    "name_kz": "Қ. Жұбанов атындағы Ақтөбе өңірлік университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 80,
    "name_kz": "Қ. и. Сәтбаев атындағы Қазақ ұлттық техникалық зерттеу университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": "https://satbayev.university/",
    "logo_url": "assets/university-logos/satbayev-university.svg",
    "logo_source_url": "https://satbayev.university/",
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 81,
    "name_kz": "Қазақ спорт және туризм академиясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 82,
    "name_kz": "Қазақ технология және бизнес университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 83,
    "name_kz": "Қазақ ұлттық аграрлық зерттеу университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 84,
    "name_kz": "Қазақ ұлттық хореография академиясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 85,
    "name_kz": "Қазақ ұлттық қыздар педагогикалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 86,
    "name_kz": "Қазақ ұлттық өнер академиясы.Т. Жүргенова",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 87,
    "name_kz": "Қазақ ұлттық өнер университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 88,
    "name_kz": "Қазақ-орыс халықаралық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 89,
    "name_kz": "Қазақстан инновациялық және телекоммуникациялық жүйелер университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 90,
    "name_kz": "Қазақстан-Америка еркін университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 91,
    "name_kz": "Қазақстан-Британ техникалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": "ҚБТУ",
    "city": "Алматы",
    "official_website": "https://kbtu.edu.kz/",
    "logo_url": "assets/university-logos/kbtu-university.svg",
    "logo_source_url": "https://kbtu.edu.kz/",
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 92,
    "name_kz": "Қазақстан-Неміс университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 93,
    "name_kz": "Қазақстан-Ресей медициналық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 94,
    "name_kz": "Қазтұтынуодағы Қарағанды университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 95,
    "name_kz": "Қайнар \" Академиясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 96,
    "name_kz": "Қарағанды индустриалды университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 97,
    "name_kz": "Қарағанды медицина университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 98,
    "name_kz": "Қонаев Университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 99,
    "name_kz": "Қорқыт Ата атындағы Қызылорда университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 100,
    "name_kz": "Қызылорда ашық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 101,
    "name_kz": "Құрманғазы атындағы Қазақ ұлттық консерваториясы",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 102,
    "name_kz": "Әбілқас Сағынов атындағы Қарағанды техникалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 103,
    "name_kz": "Әл-Фараби атындағы Қазақ ұлттық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": "ҚазҰУ",
    "city": "Алматы",
    "official_website": "https://www.kaznu.kz/",
    "logo_url": "assets/university-logos/kaznu-university.svg",
    "logo_source_url": "https://www.kaznu.kz/",
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  },
  {
    "id": 104,
    "name_kz": "Әлкей Марғұлан атындағы Павлодар педагогикалық университеті",
    "name_ru": null,
    "name_en": null,
    "short_name": null,
    "city": null,
    "official_website": null,
    "logo_url": null,
    "logo_source_url": null,
    "description": null,
    "university_type": null,
    "category": null,
    "status": "active",
    "created_at": "2026-05-31T00:00:00+05:00",
    "updated_at": "2026-05-31T00:00:00+05:00"
  }
];
